name = "irkop"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".opennext/dist"

[build]
command = "npm run build"
cwd = "./"

[build.upload]
format = "service-worker"

[vars]
ENVIRONMENT = "production"
WORKER_URL = "https://landing-page.irkop.workers.dev"
